### ISSUE TITLE
Add links to academic literature to the readme

### ISSUE THREAD

**Issue by physikerwelt** [dginev/LaTeXML-Plugin-MathSyntax#2]
I have the feeling that I read a publication about the functionality of this plugin. I suggest that a reference to this publication should be added to the readme file.

**Comment by dginev** [comment]
Interesting, since I don't think I ever published any literature on the plugin. A relevant piece of reading may be my MSc thesis, which attempted a similar grammar in CCG and enumerates some of the phenomena.

I have updated the README and included a link to that, thanks!
